#lang scheme
(define(qiu n)
  (define (qiuiter a b c count)
    (cond((= count(- n 1)) (+ c b a))
         (else (qiuiter b (+ a b 1) (+ c b) (+ count 1)))))
  (qiuiter 0 0 0 0))
(define (btest n)
   (define (btestiter a b count )
     (cond((= count n) a)
          (else(btestiter b (+ a b 1) ( + count 1)))))
     (btestiter 0 1 0))
(define (sumb x y)
  (define (sumiter x y c )
    (cond((> x y) c)
         (else(sumiter (+ x 1) y (+ c (btest x))))))
  (sumiter x y 0))